channels:
  - pytorch
  - defaults
  - menpo
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - python=3.7
  - pip
  - scikit-learn
  - imageio
  - matplotlib
  - pip:
    - tensorflow
    - opencv-python
    - dlib
    - pptk
