channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - setuptools=59.8.0
  - pip
  - pytorch
  - torchvision
  - scikit-learn
  - imageio
  - imageio-ffmpeg
  - matplotlib
  - dlib
  - polyscope
  - pyinstaller
  - pytest
  - pip:
    - tensorflow
    - opencv-python
    - pptk
