name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]  # ,"macos-latest", "windows-latest"
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          auto-update-conda: true
          use-only-tar-bz2: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: myenv
      - name: Conda info
        run: |
          conda list
          conda env list
          echo $CONDA_PREFIX
      - name: Get date
        id: get-date
        run: echo "::set-output name=today::$(/bin/date -u '+%Y%m%d')"
      - name: Cache conda env
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-${{ runner.os }}--${{ runner.arch }}--${{ steps.get-date.outputs.today }}-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        id: cache
      - name: Update environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: conda env update -n myenv -f environment.yml --prune
