name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
  
env:
  # Increase this value to reset cache if environment.yml has not changed
  CACHE_NUMBER: 0
  
jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: ["ubuntu-latest"]  # ,"macos-latest", "windows-latest"
        label: ["linux-64"]
        prefix: ["/usr/share/miniconda/envs/myenv"] #, "/Users/runner/miniconda3/envs/myenv",  "C:\Miniconda3\envs\myenv"
        python-version: ["3.7"]
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          auto-update-conda: true
          use-only-tar-bz2: true
          python-version: ${{ matrix.python-version }}
          activate-environment: myenv
          
      - name: Conda info
        run: |
          conda list
          conda env list
          echo $CONDA_PREFIX
          
      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        
      - name: Cache conda env
        uses: actions/cache@v3
        with:
          path: ${{ matrix.prefix }}
          key: conda-${{ matrix.label }}-${{ env.DATE }}-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
        id: cache
        
      - name: Update environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: conda env update -n myenv -f environment.yml
      
      - name: Test main
        run: |
          conda list
          conda env list
          echo $CONDA_PREFIX
          cd CapCalibrator
          python main.py --help
