name: release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
  
env:
  # Increase this value to reset cache if environment.yml has not changed
  CACHE_NUMBER: 0
  
jobs:
  build_release:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: ["ubuntu-latest"]  # ,"macos-latest", "windows-latest"
        label: ["linux-64"]
        prefix: ["/usr/share/miniconda/envs/myenv"] #, "/Users/runner/miniconda3/envs/myenv",  "C:\Miniconda3\envs\myenv"
        python-version: ["3.7"]
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          auto-update-conda: true
          use-only-tar-bz2: true
          python-version: ${{ matrix.python-version }}
          activate-environment: myenv
          
      - name: Conda info
        run: |
          conda list
          conda env list
          echo $CONDA_PREFIX
          
      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        
      - name: Cache conda env
        uses: actions/cache@v3
        with:
          path: ${{ matrix.prefix }}
          key: conda-${{ matrix.label }}-${{ env.DATE }}-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
        id: cache
        
      - name: Update environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: conda env update -n myenv -f environment.yml
      
      - name: Test main
        run: |
          conda list
          conda env list
          echo $CONDA_PREFIX
          cd CapCalibrator
          python main.py --help
          
      - name: Build main
        run: |
          pwd
          cd CapCalibrator
          pyinstaller main.spec
      
      - name: version
        run: |
          echo "::set-output name=version::$(./CapCalibrator/dist/main/main --version)"
          id: version
        
      - name: Archive release
        uses: thedoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          filename: ${{ matrix.label }}.zip
          path: './CapCalibrator/dist/main'
      
      - name: Print content
        run: |
          ls
          ls CapCalibrator
          ls CapCalibrator/dist
          ls CapCalibrator/dist/main
          
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ matrix.label }}.zip
          asset_name: ${{ matrix.label }}.zip
          asset_content_type: application/zip
          
      
